services:
  nrl_project:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080"
    volumes:
    - ${HOME}/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
    - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    - ${HOME}/.aspnet/https:/home/app/.aspnet/https:ro
    - ${HOME}/.aspnet/https:/root/.aspnet/https:ro