// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NRL_PROJECT.Data;

#nullable disable

namespace NRL_PROJECT.Migrations
{
    [DbContext(typeof(NRL_Db_Context))]
    [Migration("20251015110452_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NRL_PROJECT.Models.ObstacleData", b =>
                {
                    b.Property<int>("ObstacleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ObstacleId"));

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("ObstacleDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ObstacleHeight")
                        .HasColumnType("int");

                    b.Property<string>("ObstacleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObstacleType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ObstacleWidth")
                        .HasColumnType("int");

                    b.HasKey("ObstacleId");

                    b.ToTable("Obstacles");
                });

            modelBuilder.Entity("NRL_PROJECT.Models.ObstacleReportData", b =>
                {
                    b.Property<int>("Report_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Report_Id"));

                    b.Property<int>("ObstacleId")
                        .HasColumnType("int");

                    b.Property<string>("Reported_Item")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Reported_Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Time_of_Submitted_Report")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Report_Id");

                    b.HasIndex("ObstacleId");

                    b.ToTable("ObstacleReports");
                });

            modelBuilder.Entity("NRL_PROJECT.Models.ObstacleReportData", b =>
                {
                    b.HasOne("NRL_PROJECT.Models.ObstacleData", "Obstacle")
                        .WithMany("Reports")
                        .HasForeignKey("ObstacleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obstacle");
                });

            modelBuilder.Entity("NRL_PROJECT.Models.ObstacleData", b =>
                {
                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
